name: Build and push

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  push_to_gitflic:
    name: Push commits to GitFlic
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2

      - name: Put ssh key
        shell: bash
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GITFLIC_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
      - name: Delete dir .github/
        run: |
          git config --global user.email "commit-from-github@liis.su"
          git config --global user.name "commit-from-github-liis-su"
          rm -r .github
          git add .
          git commit -m 'fix'

      - name: Resolve conflicts between github and gitflic repositories
        run: |
          git remote add gitflic-1 https://gitflic.ru/project/simple-charge/test.git
          git checkout -b master-from-gitflic
          git pull gitflic master
          git branch
          git checkout ${{ github.ref }}
          git rebase master-from-gitflic
          cat .git/config
      
      - name: Pushes to another repository
        shell: bash
        run: |
          git remote add gitflic git@gitflic.ru:simple-charge/test.git
          cat .git/config
          GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no" git push --force gitflic ${{ github.ref }}:master
      
      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY
