name: Build and push

on:
  workflow_dispatch:
  push:
    branches:
      - master-gpn-onpremise
    paths-ignore:
      - '.github/**'

jobs:
  push_to_gitflic:
    name: Push commits to GitFlic
    runs-on: ubuntu-latest
    steps:
      - name: Put ssh key
        shell: bash
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GITFLIC_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
      
      - name: Pushes to another repository
        shell: bash
        run: |
          git init
          git remote add gitflic git@gitflic.ru:simple-charge/${{ github.event.repository.name }}.git
          echo $(cat .git/config) 
          GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no" git push -u gitflic --all
      
      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY
